// Pakistan-wide city list (curated; expand anytime)
const RAW_CITIES = [
    "Islamabad",
    "Rawalpindi",
    "Lahore",
    "Karachi",
    "Peshawar",
    "Multan",
    "Faisalabad",
    "Sialkot",
    "Gujranwala",
    "Hyderabad",
    "Quetta",
    "Sargodha",
    "Bahawalpur",
    "Sukkur",
    "Mardan",
    "Abbottabad",
    "Muzaffarabad",
    "Gilgit",
    "Skardu",
    "Gwadar",
    "Bagh",
    "Bhimber",
    "Kotli",
    "Mirpur",
    "Neelum",
    "Poonch",
    "Sudhnati",
    "Awaran",
    "Barkhan",
    "Bolan",
    "Chagai",
    "Dera Bugti",
    "Jafarabad",
    "Jhal Magsi",
    "Kalat",
    "Kech",
    "Kharan",
    "Khuzdar",
    "Kohlu",
    "Lasbela",
    "Loralai",
    "Mastung",
    "Musakhel",
    "Naseerabad",
    "Nushki",
    "Panjgur",
    "Pishin",
    "Qilla Abdullah",
    "Qilla Saifullah",
    "Sibi",
    "Zhob",
    "Ziarat",
    "Bajaur Agency",
    "Khyber Agency",
    "Kurram Agency",
    "Mohmand Agency",
    "North Waziristan Agency",
    "Orakzai Agency",
    "South Waziristan Agency",
    "Chilas",
    "Ghizer",
    "Hunza",
    "Abbottabad",
    "Bannu",
    "Batagram",
    "Buner",
    "Charsadda",
    "Chitral",
    "Dera Ismail Khan",
    "Dir Lower",
    "Dir Upper",
    "Hangu",
    "Haripur",
    "Karak",
    "Kohat",
    "Kohistan",
    "Lakki Marwat",
    "Malakand",
    "Mansehra",
    "Mardan",
    "Nowshera",
    "Shangla",
    "Swabi",
    "Swat",
    "Tank",
    "Alipur",
    "Attock",
    "Bahawalnagar",
    "Bhakkar",
    "Chakwal",
    "Chiniot",
    "Dera Ghazi Khan",
    "Hafizabad",
    "Jhang",
    "Jhelum",
    "Kabirwala",
    "Kasur",
    "Khanewal",
    "Khushab",
    "Layyah",
    "Lodhran",
    "Mandi Bahauddin",
    "Mianwali",
    "Muzaffargarh",
    "Nankana Sahib",
    "Narowal",
    "Okara",
    "Pakpattan",
    "Rahim Yar Khan",
    "Rajanpur",
    "Sahiwal",
    "Sheikhupura",
    "Shekhupura",
    "Toba Tek Singh",
    "Vehari",
    "Badin",
    "Dadu",
    "Ghotki",
    "Jacobabad",
    "Jamshoro",
    "Kashmore",
    "Khairpur",
    "Larkana",
    "Matiari",
    "Mirpur Khas",
    "Naushahro Feroze",
    "Nawabshah",
    "Qambar Shahdadkot",
    "Sanghar",
    "Shikarpur",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Tharparkar",
    "Thatta",
    "Umerkot"
];

export const PAK_CITIES = Array.from(new Set(RAW_CITIES.map((c) => c.trim()).filter(Boolean))).sort((a, b) =>
    a.localeCompare(b)
);
